# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saytalk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hash_tag',
            name='hash_relation_say',
            field=models.ManyToManyField(related_name='hash_set_say', through='collection.Hash_Relationship', to='saytalk.SayTalk'),
        ),
        migrations.AddField(
            model_name='hash_tag',
            name='hash_relation_user',
            field=models.ManyToManyField(related_name='hash_set_users', through='collection.Hash_Relationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hash_relationship',
            name='hash_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Hash_Tag'),
        ),
        migrations.AddField(
            model_name='hash_relationship',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hash_relationship',
            name='say_talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saytalk.SayTalk'),
        ),
    ]
