# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saytalk', '0001_initial'),
        ('collection', '0002_auto_20161122_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='say_talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saytalk.SayTalk'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='image',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
