# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_by', models.CharField(max_length=28)),
                ('created_date', models.DateTimeField(editable=False)),
                ('requested_to', models.CharField(max_length=28)),
                ('unopen_flag', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SayTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=28)),
                ('modified_by', models.CharField(max_length=28)),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_parent', models.BooleanField(default=True)),
                ('is_chat', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='sayhistory',
            name='say_talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saytalk.SayTalk'),
        ),
    ]
